application: mealsloth-hydra-ap01
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.pack$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.csslintrc$
- ^(.*/)?.*/\.idea/\.*$
- ^(.*/)?.*/\.git/\.*$

handlers:
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.5"
- name: MySQLdb
  version: "1.2.5"